### ISSUE TITLE
homebrew formula causes repeated complaints

### ISSUE THREAD

**Issue by JonathanDoughty** [capnfabs/grouse#19]
With grouse 0.2 installed via homebrew, current versions of homebrew complain on each update:

> Warning: Calling bottle :unneeded is deprecated! There is no replacement.
> Please report this issue to the capnfabs/tap tap (not Homebrew/brew or Homebrew/core):
>   /usr/local/Homebrew/Library/Taps/capnfabs/homebrew-tap/grouse.rb:6

I _think_ this may be a result of [goreleaser's deprecation](https://goreleaser.com/deprecations/?h=brew#brewsgithub) of the [github](https://github.com/capnfabs/grouse/blob/3ec82a30a5a8860ff0043ceebef60a37601fd7ae/.goreleaser.yml#L29) section used in the current `.goreleaser.yml`, which I presume would require an update to the grouse.rb homebrew tap.

That is largely speculation on my part however, though it does seem to be a now fixed [bug in goreleaser](https://github.com/goreleaser/goreleaser/issues/2595)

**Comment by capnfabs** [comment]
Thanks for the report and the preliminary investigation! That sounds like a plausible explanation; I'll look into it when I get time.

**Comment by capnfabs** [comment]
Hey @JonathanDoughty! Just wanted to say thank again for filing this; I just ran into this when trying to install `grouse` on a new machine and it made diagnosing / fixing the issue super easy.

Issue's fixed now; installing with `brew install capnfabs/tap/grouse` is working again.
